sudo: required
services:
  - docker            // we want access to docker client

env:
  global:
    - SHA=$(git rev-parse HEAD)
    
language: java
jdk:
  - oraclejdk11

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin



script:
  - docker build -t maheshkumarctl/docker-k8s-example:"$SHA" .
  - docker push maheshkumarctl/docker-k8s-example:"$SHA"
  - docker run --publish 192.168.99.1:8097:8080 maheshkumarctl/docker-k8s-example:"$SHA"
  - docker ps -a
  - docker-machine ip
  
  




