sudo: required
services:
  - docker            // we want access to docker client

language: java
jdk:
  - oraclejdk11

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t maheshkumarctl/docker-k8s-example:latest .



script:
  - mvn clean install
  - docker build -t maheshkumarctl/docker-k8s-example:latest .
  - docker push maheshkumarctl/docker-k8s-example:latest



