sudo: required
services:
  - docker            // we want access to docker client

language: java
jdk:
  - oraclejdk11

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin



script:
  - mvn clean install
