sudo: required
services:
  - docker            // we want access to docker client
env:                                                        // *** creating environment variables so that other scripts can access them
  global:
    - SHA=$(git rev-parse HEAD)                             // ***  this gives the commit id# (this is unique) of the last commit that
                                                            //      was done.

language: java
jdk:
  - oraclejdk11



script:
  - mvn clean install
//  - docker run stephengrider/react-test npm test -- --coverage
//  - docker build -t maheshkumarctl/docker-k8s-example:"$SHA" .
//  - docker push maheshkumarctl/docker-k8s-example:"$SHA"

//echo "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY"
