sudo: required
services:
  - docker            // we want access to docker client

language: java
jdk:
  - oraclejdk11

before_install:
// ********* Giving the docker client access to our Docker Hub account
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  


script:
  - mvn clean install
