sudo: required
services:
  - docker            // we want access to docker client
env:                                                        // *** creating environment variables so that other scripts can access them
  global:
    - SHA=$(git rev-parse HEAD)                             // ***  this gives the commit id# (this is unique) of the last commit that

language: java
jdk:
  - oraclejdk11



script:
  - mvn clean install
