sudo: required
services:
  - docker            // we want access to docker client

language: java
jdk:
  - oraclejdk11

before_install:
// ********* Giving the docker client access to our Docker Hub account
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
// ********* Building an image    -t : name of the image  Dockerfile to use
  - docker build -t maheshkumarctl/docker-k8s-example:latest .



script:
  - mvn clean install
