sudo: required

language: java
jdk:
  - oraclejdk11



script:
  - mvn clean install
//  - docker run stephengrider/react-test npm test -- --coverage
//  - docker build -t maheshkumarctl/docker-k8s-example:"$SHA" .
//  - docker push maheshkumarctl/docker-k8s-example:"$SHA"

//echo "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY"
